4.1 Exercise on Functions:
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [1]:
def convert_length (value, unit) :
  if unit == 'm':
    return value * 3.28084
  elif unit == 'ft':
    return value / 3.28084
  else:
    raise ValueError("Unsupported length unit")
def convert_weight (value, unit):
  if unit == 'kg':
    return value * 2.20462
  elif unit == 'lb':
    return value / 2.20462
  else :
    raise ValueError("Unsupported weight unit");

def convert_volume (value, unit):
  if unit == 'l' :
    return value * 0.264172
  elif unit == 'gal' :
    return value / 0.264172
  else :
    raise ValueError("Unsupported volume unit")
def main() :
  print("Choose conversion type : \n 1. Length (m-ft) \n 2. Weight (lg-lbs) \n 3. Volume (L-gal) \n")
  try :
    choice = int(input("Enter your choice (1/2/3) : "))
    if choice not in [1, 2, 3] :
      print("Invalid choice. Please enter 1/2/3")
      return
    value = int(input("Enter value to convert: "))
    if choice == 1 :
      unit = input("Enter unit (m/ft) : ")
      print(f"Converted value : {convert_length(value, unit)}")
    elif choice == 2 :
      unit = input("Enter unit (kg/lb) : ")
      print(f"Converted value : {convert_weight(value, unit)}")
    elif choice == 3 :
      unit = input("Enter unit (l/gal) : ")
      print(f"Converted value : {convert_volume(value, unit)}")
  except ValueError as e :
      print(f"Error: {e}. Please enter a valid numeric value and unit")
  except Exception as e :
      print(f"An unexpected error occurred: {e}")
if __name__ == "__main__":
  main()





Choose conversion type : 
 1. Length (m-ft) 
 2. Weight (lg-lbs) 
 3. Volume (L-gal) 

Enter your choice (1/2/3) : `1
Error: invalid literal for int() with base 10: '`1'. Please enter a valid numeric value and unit


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [2]:
def calculate_sum(numbers):
  return sum(numbers)

def calculates_average(numbers):
  return sum(numbers) / len(numbers) if numbers else 0

def find_max(numbers):
  return max(numbers) if numbers else None

def find_min(numbers):
  return min(numbers) if numbers else None
def main():
  print("Choose an operation")
  print("1. Calculate Sum")
  print("2. Calculate Average")
  print("3. Find Maximum")
  print("4. Find Minimum")
  try:
    choice = int(input("Enter your choice (1/2/3/4): "))
    if choice not in [1, 2, 3, 4]:
      print("Invalid choice. Please enter 1/2/3/4")
      return

    user_input = input("Enter a list of numbers separated by spaces: ")
    numbers = list(map(float, user_input.split()))

    if not numbers:
      print("Numbers cannot be zero")
      return
    if choice == 1:
      print(f"Sum of numbers: {calculate_sum(numbers)}")
    elif choice == 2:
      print(f"Average of numbers: {calculates_average(numbers)}")
    elif choice == 3:
      print(f"Maximum value: {find_max(numbers)}")
    elif choice == 4:
      print(f"Minimum value: {find_min(numbers)}")
  except ValueError as e:
    print(f"Error: {e}. Please enter a valid list of numbers")
  except Exception as e:
    print(f"An unexpected error occurred: {e}")
if __name__ == "__main__":
  main()

Choose an operation
1. Calculate Sum
2. Calculate Average
3. Find Maximum
4. Find Minimum
Enter your choice (1/2/3/4): 1
Enter a list of numbers separated by spaces: 1
Sum of numbers: 1.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [3]:
def extract_every_other(lst):

  return lst[::2]

numbers = [1,2,3,4,5,6]
result = extract_every_other(numbers)
print(result)

[1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [4]:
def get_sublist(lst, start, end):
    return lst[start:end+1]


numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)
print(result)


[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [5]:
def reverse_list(lst):
    return lst[::-1]


input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)

print(output_list)


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [6]:
def remove_first_last(lst):
    return lst[1:-1]
input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)

print(output_list)


[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [7]:
def get_first_n(lst, n):
    return lst[:n]
input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)

print(output_list)


[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [8]:
def get_last_n(lst, n):
    return lst[-n:]
input_list = [1, 2, 3, 4, 5]
n = 2
output_list = get_last_n(input_list, n)

print(output_list)


[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [9]:
def reverse_skip(lst):
    return lst[-2::-2]
input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)

print(output_list)


[5, 3, 1]


4.3 Exercise on Nested List:


In [10]:

from itertools import chain

def flatten_nested(lst):
    return list(chain.from_iterable(
        flatten_nested(item) if isinstance(item, list) else [item]
        for item in lst
    ))

def get_element(lst, indices):
    return lst if not indices else get_element(lst[indices[0]], indices[1:])

def sum_all(lst):
    return sum(
        sum_all(item) if isinstance(item, list) else item
        for item in lst
    )

def filter_value(lst, target):
    return [
        filter_value(item, target) if isinstance(item, list) else item
        for item in lst if item != target
    ]

def max_value(lst):
    return max(
        (max_value(item) if isinstance(item, list) else item for item in lst),
        default=float('-inf')
    )

def count_occurrences(lst, target):
    return sum(
        count_occurrences(item, target) if isinstance(item, list) else (item == target)
        for item in lst
    )

def deep_flatten(lst):
    for item in lst:
        if isinstance(item, list):
            yield from deep_flatten(item)
        else:
            yield item

def average_all(lst):
    elements = list(deep_flatten(lst))
    return sum(elements) / len(elements) if elements else 0


In [11]:
nested_lst = [[1, 2], [3, [4, 5]], 6]
print(flatten_nested(nested_lst))
print(get_element(nested_lst, [1, 1]))
print(sum_all(nested_lst))
nested_lst2 = [[1, 2], [3, 2], [4, 5]]
print(filter_value(nested_lst2, 2))
print(max_value(nested_lst))
print("Occurrences of 2:", count_occurrences(nested_lst2, 2))
nested_lst3 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_lst3))
nested_lst4 = [[1, 2], [3, 4], [5, 6]]
print(average_all(nested_lst4))

[1, 2, 3, 4, 5, 6]
[4, 5]
21
[[1], [3], [4, 5]]
6
Occurrences of 2: 2
<generator object deep_flatten at 0x7da571e37ae0>
3.5


10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [12]:
import numpy as np

empty_matrix = np.empty((2, 2))
print(empty_matrix)

ones_matrix = np.ones((4, 2))
print("\n", ones_matrix)

matrix_shape = (3, 3)
fill_num = 7
filled_matrix = np.full(matrix_shape, fill_num)
print("\n", filled_matrix)

array_sample = np.array([[1, 2], [3, 4]])
zeros_clone = np.zeros_like(array_sample)
print("\n", zeros_clone)

ones_clone = np.ones_like(array_sample)
print("\n", ones_clone)

num_list = [1, 2, 3, 4]
numpy_arr = np.array(num_list)
print("\n", numpy_arr)


[[1.90848280e-316 0.00000000e+000]
 [6.82549436e-310 5.32930826e-317]]

 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 [[0 0]
 [0 0]]

 [[1 1]
 [1 1]]

 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [13]:
import numpy as np

num_sequence = np.arange(10, 50)
print("\n", num_sequence)

reshaped_arr = np.arange(9).reshape(3, 3)
print("\n", reshaped_arr)

identity_matrix = np.eye(3)
print("\n", identity_matrix)

random_values = np.random.random(30)
mean_random_values = random_values.mean()
print("\n", random_values)
print("\nMean", mean_random_values)

random_matrix = np.random.random((10, 10))
min_element = random_matrix.min()
max_element = random_matrix.max()
print("\n", random_matrix)
print("\nMinimum", min_element)
print("\nMaximum", max_element)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\n", zero_array)

original_array = np.array([1, 2, 0, 0, 4, 0])
reversed_array = original_array[::-1]
print("\n", reversed_array)

border_matrix = np.ones((5, 5))
border_matrix[1:-1, 1:-1] = 0
print("\n", border_matrix)

# Creating a chessboard pattern
chessboard_pattern = np.zeros((8, 8), dtype=int)
chessboard_pattern[1::2, ::2] = 1
chessboard_pattern[::2, 1::2] = 1
print("\n", chessboard_pattern)



 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [0.49126736 0.86821231 0.1214952  0.88472697 0.52623214 0.96315654
 0.30351705 0.41367855 0.69536785 0.18736936 0.97407737 0.79844946
 0.49867655 0.34763804 0.50197943 0.20969773 0.15269042 0.94713377
 0.5865686  0.58013186 0.43979448 0.23811723 0.67033456 0.2349686
 0.81186643 0.73016609 0.86267887 0.47919911 0.19351564 0.96746005]

Mean 0.5560055881329383

 [[7.36155991e-02 5.49023401e-01 8.90791431e-01 8.26387610e-01
  9.37027409e-01 7.34794922e-01 9.86379071e-01 2.31112677e-01
  6.80246673e-01 5.42348225e-01]
 [3.73594724e-01 6.07372801e-01 5.04072146e-01 2.58071644e-01
  2.23738749e-01 5.68610502e-01 3.43244993e-01 2.24697465e-01
  7.37848914e-01 6.82205334e-01]
 [9.15335658e-01 1.10234136e-01 9.05456348e-01 3.84010377e-01
  2.66218267e-01 6.48975372e-01 4.59153498e-01 2.69827156e-01
  4.

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [14]:
import numpy as np

a = np.array([[1, 2], [3, 5]])
b = np.array([[5, 6], [7, 8]])
u = np.array([9, 10])
v = np.array([11, 12])

# Addition
sum_ab = a + b
print("Sum of a and b:\n", sum_ab)

# Subtraction
diff_ab = a - b
print("Difference of a and b:\n", diff_ab)

# Multiplication
mul_a = a * 2
mul_b = b * 3
print("Multiplying a by 2:\n", mul_a)
print("Multiplying b by 3:\n", mul_b)

# Dot product
dot_uv = np.dot(u, v)
dot_av = np.dot(a, u)
dot_ab = np.dot(a, b)

print("Dot product of u and v:", dot_uv)
print("Dot product of a and u:\n", dot_av)
print("Dot product of a and b:\n", dot_ab)

# Concatenation
concat_ab_row = np.concatenate((a, b), axis=0)
concat_uv_col = np.concatenate((u.reshape(-1, 1), v.reshape(-1, 1)), axis=1)

print("Concatenating a and b along row:\n", concat_ab_row)
print("Concatenating u and v along column:\n", concat_uv_col)


Sum of a and b:
 [[ 6  8]
 [10 13]]
Difference of a and b:
 [[-4 -4]
 [-4 -3]]
Multiplying a by 2:
 [[ 2  4]
 [ 6 10]]
Multiplying b by 3:
 [[15 18]
 [21 24]]
Dot product of u and v: 219
Dot product of a and u:
 [29 77]
Dot product of a and b:
 [[19 22]
 [50 58]]
Concatenating a and b along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenating u and v along column:
 [[ 9 11]
 [10 12]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [15]:
import numpy as np

M = np.array([[3, 4], [7, 8]])
N = np.array([[5, 3], [2, 1]])

# Calculate inverse of M
M_inv = np.linalg.inv(M)
identity_check = np.dot(M, M_inv)
print("M * M_inv:\n", identity_check)

# Matrix multiplication
MN = np.dot(M, N)
NM = np.dot(N, M)
print("MN:\n", MN)
print("NM:\n", NM)

# Transpose verification
MN_Tp = MN.T
NTp_MTp = np.dot(N.T, M.T)
print("Transpose of MN:\n", MN_Tp)
print("N^T * M^T:\n", NTp_MTp)

# Solving system of equations
E = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
F = np.array([[-1], [-3], [9]])

E_inv = np.linalg.inv(E)
result_1 = np.dot(E_inv, F)
print("\nSolution using inverse:\n", result_1)

result_2 = np.linalg.solve(E, F)
print("\nSolution using np.linalg.solve:\n", result_2)


M * M_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
MN:
 [[23 13]
 [51 29]]
NM:
 [[36 44]
 [13 16]]
Transpose of MN:
 [[23 51]
 [13 29]]
N^T * M^T:
 [[23 51]
 [13 29]]

Solution using inverse:
 [[ 2.]
 [ 1.]
 [-2.]]

Solution using np.linalg.solve:
 [[ 2.]
 [ 1.]
 [-2.]]
